---
title: "Untitled"
author: "Scott McKean"
date: "10/8/2019"
output: html_document
---

```{r setup}
library(duvernaygeomechmodel)
set.seed(1)
```

Load datasets, encode factors, and set brittleness with residual data

```{r}
mldf_nores = read_csv("../data/merged_tests_no_residual.csv") %>%
  mutate(horiz_orient = ifelse(orientation == 'horizontal', 1, 0)) %>%
  mutate(shale_group = ifelse(group == 'shale', 1, 0)) %>% 
  as.data.frame()

mldf_wres = read_csv("../data/merged_tests_w_residual.csv") %>%
  mutate(brittleness = (peak_stress_dev - residual_stress_dev)/peak_stress_dev) %>%
  mutate(horiz_orient = ifelse(orientation == 'horizontal', 1, 0)) %>%
  mutate(shale_group = ifelse(group == 'shale', 1, 0)) %>%
  as.data.frame()
```

```{r}
feat_set = c('pred_vp', 'bulk_density', 'horiz_orient', 'shale_group')
feat_pref = 'vp_rho'

generate_models(mldf_nores, feats = feat_set, 
  targets = c("youngs_modulus", "poisson_ratio"), feat_prefix = feat_pref)

generate_models(mldf_wres, feats = feat_set, 
  targets = c("brittleness"), feat_prefix = feat_pref)
```

```{r}
feat_set = c('pred_vp', 'bulk_density', 'pred_vs', 'horiz_orient', 'shale_group')
feat_pref = 'vp_vs_rho'

generate_models(mldf_nores, feats = feat_set, 
  targets = c("youngs_modulus", "poisson_ratio"), feat_prefix = feat_pref)

generate_models(mldf_wres, feats = feat_set, 
  targets = c("brittleness"), feat_prefix = feat_pref)
```

```{r}
feat_set = c('deviatoric_stress', 'pred_vp', 'bulk_density', 'horiz_orient', 'shale_group')
feat_pref = 'dev_vp_rho'

generate_models(mldf_nores, feats = feat_set, 
  targets = c("youngs_modulus", "poisson_ratio"), feat_prefix = feat_pref)

generate_models(mldf_wres, feats = feat_set, 
  targets = c("brittleness"), feat_prefix = feat_pref)
```

```{r}
feat_set = c('deviatoric_stress', 'pred_vs', 'pred_vp', 'bulk_density', 'horiz_orient', 'shale_group')
feat_pref = 'dev_vp_vs_rho'

generate_models(mldf_nores, feats = feat_set, 
  targets = c("youngs_modulus", "poisson_ratio"), feat_prefix = feat_pref)

generate_models(mldf_wres, feats = feat_set, 
  targets = c("brittleness"), feat_prefix = feat_pref)
```

```{r}
feat_set = c('deviatoric_stress', 'confining_pressure', 'pred_vp', 'bulk_density', 'horiz_orient', 'shale_group')
feat_pref = 'dev_conf_vp_rho'

generate_models(mldf_nores, feats = feat_set, 
  targets = c("youngs_modulus", "poisson_ratio"), feat_prefix = feat_pref)

generate_models(mldf_wres, feats = feat_set, 
  targets = c("brittleness"), feat_prefix = feat_pref)
```

```{r}
feat_set = c('deviatoric_stress', 'confining_pressure', 'pred_vs', 'pred_vp', 'bulk_density', 'horiz_orient', 'shale_group')
feat_pref = 'dev_conf_vp_vs_rho'

generate_models(mldf_nores, feats = feat_set, 
  targets = c("youngs_modulus", "poisson_ratio"), feat_prefix = feat_pref)

generate_models(mldf_wres, feats = feat_set, 
  targets = c("brittleness"), feat_prefix = feat_pref)
```
