---
title: "las_reader"
output: html_document
---

```{r setup, include=FALSE}
source('../R/read_las_files.R')
library(tidyverse)
library(janitor)
library(data.table)
library(plot3D)
library(viridis)
library(raster)
library(sf)
# set study bounds
study_bound_coords <- rbind(
  c(460000, 5980000), c(460000, 6080000), c(560000, 6080000), 
  c(560000, 5980000), c(460000, 5980000)
  )

# make a polygon
study_bounds <- list(study_bound_coords) %>%
  st_polygon() %>%
  st_sfc(., crs = 26911) %>%
  st_sf(.)

study_proj = st_crs(study_bounds)$proj4string

# make a 2500x2500 m raster
study_raster <- raster(
  extent(study_bounds), 
  resolution = 2500,
  crs = st_crs(study_bounds)$proj4string
  )
```

# Load surface locations

```{r}
surface_locs = sf::st_read(
  dsn = '../data-raw/sh_shapefile/', layer='ST37_SH_GCS_NAD83') %>% 
  st_transform(., crs = 26911)

study_locs = surface_locs %>% filter(
  st_within(surface_locs, study_bounds,sparse = FALSE)
  )

well_list = read_tsv(
  '../data-raw/sh_shapefile/WellList.txt', 
  col_names = c('uwi_disp','uwi','flag','name','field','pool','os_area',
                'os_dep','license', 'status', 'issue_data', 'code','agent', 
                'operator','drill_data', 'td_m','stat_code', 'stat_date', 
                'fluid', 'mode', 'struct', 'scheme', 'scheme_sub')
  )



# Filter to study bounds
```

# Find las files and uwis

```{r}
files <- list.files('../data-raw/las_files/', full.names = FALSE)

short_uwis <- files %>%
    str_replace_all(., '.las', '') %>%
    str_replace_all(., 'w', 'W')
```

# See how many coordinates we have

```{r}
(short_uwis %in% wheaders$unformatted_api_uwi) %>% sum()

```

# Try out Read Las Functions on desired wells

```{r}


# load log files
# get uwis in study bounds
# read las files
# pull out duvernay bounds using top/bottom surfaces from AGS
# 


get_log_data <- function(file){
  short_uwi <- file %>%
    str_replace(., './duvernay_las_files/', '') %>%
    str_replace(., '.las', '') %>%
    str_replace_all(., 'w', 'W')
  
  readLASFileIntoTable(file, short = short_uwi)
}

log_list <- map(.x = files_filt, get_log_data)

log_names <- map(.x = log_list, .f = colnames) %>%
  unlist() %>%
  unique()

logs_df <- bind_rows(log_list) %>%
  janitor::clean_names()

logs_df %>%
  group_by(uwi) %>%
  summarise(rows = n(), 
            rhob = sum(na.omit(rhob_qcgeo_k_m) > 0),
            dtc = sum(na.omit(dtc_qcgeo_us_m) > 0),
            dts = sum(na.omit(dts_qcgeo_us_m) > 0 ))

# all logs have density (and thus vertical stress)
# 12/13 logs have compressional sonic
# 10/13 logs have shear sonic

write.csv(logs_df, 'duvernay_las_processed.csv')

logs_df <- read_csv('duvernay_las_processed.csv')
library(lasoo)
```
# Queue up the entire log set for the duvernay to see how many have dtc vs dts. 

```{r}
all_log_list <- map(.x = files[1], get_log_data)

write_rds(all_log_list, 'test_log_list.rds')

all_log_names <- map(.x = all_log_list, .f = colnames) %>%
  unlist() %>%
  unique()

all_logs_df <- bind_rows(all_log_list) %>%
  janitor::clean_names()

write_csv(all_logs_df, 'test_logs.csv')

all_logs_summary <- all_logs_df %>%
  group_by(uwi) %>%
  summarise(rows = n(), 
            rhob = sum(na.omit(rhob_qcgeo_k_m) > 0),
            dtc = sum(na.omit(dtc_qcgeo_us_m) > 0),
            dts = sum(na.omit(dts_qcgeo_us_m) > 0))



all_logs_df %>%
  group_by(uwi) %>%
  summarise(rows = n())
```

