---
title: "Untitled"
author: "Scott McKean"
date: "10/8/2019"
output: html_document
---

```{r setup}
library(duvernaygeomechmodel)
set.seed(1)
```

Load datasets, encode factors, and set brittleness with residual data

```{r}
mldf_nores = read_csv("../data/merged_tests_no_residual.csv") %>%
  mutate(orientation = as.factor(orientation)) %>%
  mutate(group = as.factor(group))

mldf_wres = read_csv("../data/merged_tests_w_residual.csv") %>%
  mutate(brittleness = (peak_stress_dev - residual_stress_dev)/peak_stress_dev) %>%
  mutate(orientation = as.factor(orientation)) %>%
  mutate(group = as.factor(group))
```

Set features

```{r}
aux_cols <- c("well", "round_depth", "se_vp", "se_vs", "se_vp_per", "se_vs_per")

features <- c("orientation", "confining_pressure", 'pred_vs', 'pred_vp', 
                "bulk_density", "group", "deviatoric_stress")

targets <- c("youngs_modulus", "poisson_ratio", "brittleness")
```

```{r}
target = "youngs_modulus"

features =  c("orientation", "confining_pressure", 'pred_vs', 'pred_vp', 
                "bulk_density", "deviatoric_stress")

model_type = "regr.glmnet" #regr.mars, regr.ranger

pset= makeParamSet(
  makeNumericParam('alpha',lower = 0, upper = 1),
  makeIntegerParam('lambda', lower = -4, upper = 1, trafo = function(x) 10^x)
)

prefix = 'ym_glm_all'

### START FUNCTION - target, features, model_type, pset, prefix

ml_df = mldf_nores %>% 
  select(features, target)

set.seed(1)
train_rows = sample(nrow(ml_df)*0.9)
train = ml_df[train_rows,]
test = ml_df[-train_rows,]

learner = makeLearner(model_type)

train_task = makeRegrTask(data = train, target = target)
test_task = makeRegrTask(data = test, target = target)
all_task = makeRegrTask(data = ml_df, target = target)

meas = list(mlr::mae, mlr::rmse)

tune_res = tuneParams(
  learner, train_task, resampling=cv5, par.set=pset, 
  control=makeTuneControlMBO(budget = 100L),
  measures=meas
)

dir.create(paste0('../output/',prefix), showWarnings = FALSE)
write_rds(tune_res, paste0('../output/',prefix,"/tune_results.rds"))

# set hyperparameters
tuned_learner = setHyperPars(learner = learner, par.vals = tune_res$x)

# train final model for performance and interpretation
model = train(tuned_learner, train_task)
test_predict = predict(model, newdata=test)
train_predict = predict(model, newdata=train)

predictor = Predictor$new(model, data = ml_df)

# monte-carlo performance measures
resample = mlr::resample(
  tuned_learner, all_task, 
  makeResampleDesc("Subsample", iters=500, split=4/5, predict='both'),  
  measures = meas,
  show.info = FALSE
  )

model_res = get_resample_regr_res(resample)
model_res$train_perf = performance(predict(model, newdata=train), measures = meas)
model_res$test_perf = performance(predict(model, newdata=test), measures = meas)
model_res$model = model
model_res$tuned_learner = tuned_learner

sink(paste0('../output/',prefix,"/model_results.txt"))
print(model_res)
sink()

write_rds(model_res, paste0('../output/',prefix,"/resample.rds"))

# PLOT RESIDUALS
p1 = plotResiduals(train_predict,loess.smooth=FALSE) +
  geom_abline(slope=1,linetype = "dashed") +
  ggtitle("Training Set") +
  theme_minimal()

p2 = plotResiduals(test_predict,loess.smooth=FALSE) +
  geom_abline(slope=1,linetype = "dashed") +
  ggtitle("Test Set") +
  theme_minimal()

ggsave(paste0('../output/',prefix,"/residual_plot.pdf"), 
       arrangeGrob(grobs = list(p1,p2), nrow=1),
       width = 6, height = 6)

# IMPORTANCE & INTERACTION PLOTS
importance = FeatureImp$new(predictor, loss='mae', n.repetitions = 50)

p1 = ggplot(importance$results) +
  geom_col(aes(x = feature, y = importance)) +
  labs(x = 'Feature', y = 'Permutation Importance') +
  coord_flip() +
  theme_minimal()

interact = Interaction$new(predictor)

p2 = ggplot(as.data.frame(interact$results)) +
  geom_col(aes(x = .feature, y = .interaction)) +
  labs(x = '', y = 'Interaction') +
  coord_flip() +
  theme_minimal()

ggsave(file = paste0('../output/',prefix,"/imp_int_plot.pdf"), 
       arrangeGrob(grobs = list(p1,p2), ncol=1),
       width = 6, height = 6, dpi=600)

# PARTIAL DEPENDENCE PLOT
plist <- map(.x = 1:length(features), .f = make_pdp_plot,
             predictor = predictor, feats = features)

ggsave(file = paste0('../output/',prefix,"/pdpplot.pdf"), 
       arrangeGrob(grobs = plist, ncol = 3, left = target),
       width = 12, height = 6, dpi=600)
```


